### ISSUE TITLE
Socket hangup

### ISSUE THREAD

**Issue by sweebee** [markbergsma/pimatic-hue-zll#3]
Often i get this error, here a full log:

```
Unhandled rejection Error: Hue API maximum queue length (15) exceeded
    at Error (<anonymous>)
    at HueQueue.pushTask (/home/pi/pimatic-app/node_modules/pimatic-hue-zll/hue-zll.coffee:33:31)
    at BaseHueLightGroup.pollAllGroups (/home/pi/pimatic-app/node_modules/pimatic-hue-zll/hue-zll.coffee:227:26)
    at wrapper [as _onTimeout] (timers.js:252:14)
    at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)
18:30:16.430 [pimatic-hue-zll] Received light 1 state change: {"on":false,"bri":152,"alert":"none","reachable":true}
18:30:16.511 [pimatic-hap] [fa:fe:db:e4:36:2c] HAP Request: POST /pair-verify
18:30:16.527 [pimatic-hap] [fa:fe:db:e4:36:2c] Pair verify step 1/2
18:30:16.855 [pimatic-hue-zll] Received light 3 state change: {"on":true,"bri":211,"hue":14529,"sat":160,"effect":"none","xy":[0.4708,0.4124],"ct":389,"alert":"none","colormode":"xy","reachable":true}
18:30:18.103 [pimatic-hue-zll] Hue API request failed: socket hang up
18:30:18.111 [pimatic] Could not get attribute value of Ornamenten.state: socket hang up
18:30:18.115 [pimatic] Error: socket hang up
18:30:18.115 [pimatic]>    at createHangUpError (http.js:1472:15)
18:30:18.115 [pimatic]>    at Socket.socketOnEnd (http.js:1568:23)
18:30:18.115 [pimatic]>    at Socket.g (events.js:180:16)
18:30:18.115 [pimatic]>    at Socket.EventEmitter.emit (events.js:117:20)
18:30:18.115 [pimatic]>    at _stream_readable.js:920:16
18:30:18.115 [pimatic]>    at process._tickCallback (node.js:415:13)
18:30:18.119 [pimatic] Could not get attribute value of Ornamenten.reachable: socket hang up
18:30:18.122 [pimatic] Error: socket hang up
18:30:18.122 [pimatic]>    at createHangUpError (http.js:1472:15)
18:30:18.122 [pimatic]>    at Socket.socketOnEnd (http.js:1568:23)
18:30:18.122 [pimatic]>    at Socket.g (events.js:180:16)
18:30:18.122 [pimatic]>    at Socket.EventEmitter.emit (events.js:117:20)
18:30:18.122 [pimatic]>    at _stream_readable.js:920:16
18:30:18.122 [pimatic]>    at process._tickCallback (node.js:415:13)
18:30:18.133 [pimatic] Could not get attribute value of Ornamenten.dimlevel: socket hang up
18:30:18.137 [pimatic] Error: socket hang up
18:30:18.137 [pimatic]>    at createHangUpError (http.js:1472:15)
18:30:18.137 [pimatic]>    at Socket.socketOnEnd (http.js:1568:23)
18:30:18.137 [pimatic]>    at Socket.g (events.js:180:16)
18:30:18.137 [pimatic]>    at Socket.EventEmitter.emit (events.js:117:20)
18:30:18.137 [pimatic]>    at _stream_readable.js:920:16
18:30:18.137 [pimatic]>    at process._tickCallback (node.js:415:13)
18:30:18.141 [pimatic] Could not get attribute value of Ornamenten.hue: socket hang up
18:30:18.143 [pimatic] Error: socket hang up
18:30:18.143 [pimatic]>    at createHangUpError (http.js:1472:15)
18:30:18.143 [pimatic]>    at Socket.socketOnEnd (http.js:1568:23)
18:30:18.143 [pimatic]>    at Socket.g (events.js:180:16)
18:30:18.143 [pimatic]>    at Socket.EventEmitter.emit (events.js:117:20)
18:30:18.143 [pimatic]>    at _stream_readable.js:920:16
18:30:18.143 [pimatic]>    at process._tickCallback (node.js:415:13)
18:30:18.148 [pimatic] Could not get attribute value of Ornamenten.sat: socket hang up
18:30:18.150 [pimatic] Error: socket hang up
18:30:18.150 [pimatic]>    at createHangUpError (http.js:1472:15)
18:30:18.150 [pimatic]>    at Socket.socketOnEnd (http.js:1568:23)
18:30:18.150 [pimatic]>    at Socket.g (events.js:180:16)
18:30:18.150 [pimatic]>    at Socket.EventEmitter.emit (events.js:117:20)
18:30:18.150 [pimatic]>    at _stream_readable.js:920:16
18:30:18.150 [pimatic]>    at process._tickCallback (node.js:415:13)
18:30:18.155 [pimatic] Could not get attribute value of Ornamenten.colormode: socket hang up
18:30:18.157 [pimatic] Error: socket hang up
18:30:18.157 [pimatic]>    at createHangUpError (http.js:1472:15)
18:30:18.157 [pimatic]>    at Socket.socketOnEnd (http.js:1568:23)
18:30:18.157 [pimatic]>    at Socket.g (events.js:180:16)
18:30:18.157 [pimatic]>    at Socket.EventEmitter.emit (events.js:117:20)
18:30:18.157 [pimatic]>    at _stream_readable.js:920:16
18:30:18.157 [pimatic]>    at process._tickCallback (node.js:415:13)
18:30:18.161 [pimatic] Could not get attribute value of Ornamenten.ct: socket hang up
18:30:18.164 [pimatic] Error: socket hang up
18:30:18.164 [pimatic]>    at createHangUpError (http.js:1472:15)
18:30:18.164 [pimatic]>    at Socket.socketOnEnd (http.js:1568:23)
18:30:18.164 [pimatic]>    at Socket.g (events.js:180:16)
18:30:18.164 [pimatic]>    at Socket.EventEmitter.emit (events.js:117:20)
18:30:18.164 [pimatic]>    at _stream_readable.js:920:16
18:30:18.164 [pimatic]>    at process._tickCallback (node.js:415:13)
18:30:18.170 [pimatic] Could not update variable woonkamer-ornamenten.state: socket hang up
18:30:18.173 [pimatic] Error: socket hang up
18:30:18.173 [pimatic]>    at createHangUpError (http.js:1472:15)
18:30:18.173 [pimatic]>    at Socket.socketOnEnd (http.js:1568:23)
18:30:18.173 [pimatic]>    at Socket.g (events.js:180:16)
18:30:18.173 [pimatic]>    at Socket.EventEmitter.emit (events.js:117:20)
18:30:18.173 [pimatic]>    at _stream_readable.js:920:16
18:30:18.173 [pimatic]>    at process._tickCallback (node.js:415:13)
18:30:18.178 [pimatic] Could not update variable woonkamer-ornamenten.reachable: socket hang up
18:30:18.181 [pimatic] Error: socket hang up
18:30:18.181 [pimatic]>    at createHangUpError (http.js:1472:15)
18:30:18.181 [pimatic]>    at Socket.socketOnEnd (http.js:1568:23)
18:30:18.181 [pimatic]>    at Socket.g (events.js:180:16)
18:30:18.181 [pimatic]>    at Socket.EventEmitter.emit (events.js:117:20)
18:30:18.181 [pimatic]>    at _stream_readable.js:920:16
18:30:18.181 [pimatic]>    at process._tickCallback (node.js:415:13)
18:30:18.185 [pimatic] Could not update variable woonkamer-ornamenten.dimlevel: socket hang up
18:30:18.187 [pimatic] Error: socket hang up
18:30:18.187 [pimatic]>    at createHangUpError (http.js:1472:15)
18:30:18.187 [pimatic]>    at Socket.socketOnEnd (http.js:1568:23)
18:30:18.187 [pimatic]>    at Socket.g (events.js:180:16)
18:30:18.187 [pimatic]>    at Socket.EventEmitter.emit (events.js:117:20)
18:30:18.187 [pimatic]>    at _stream_readable.js:920:16
18:30:18.187 [pimatic]>    at process._tickCallback (node.js:415:13)
18:30:18.192 [pimatic] Could not update variable woonkamer-ornamenten.hue: socket hang up
18:30:18.194 [pimatic] Error: socket hang up
18:30:18.194 [pimatic]>    at createHangUpError (http.js:1472:15)
18:30:18.194 [pimatic]>    at Socket.socketOnEnd (http.js:1568:23)
18:30:18.194 [pimatic]>    at Socket.g (events.js:180:16)
18:30:18.194 [pimatic]>    at Socket.EventEmitter.emit (events.js:117:20)
18:30:18.194 [pimatic]>    at _stream_readable.js:920:16
18:30:18.194 [pimatic]>    at process._tickCallback (node.js:415:13)
18:30:18.198 [pimatic] Could not update variable woonkamer-ornamenten.sat: socket hang up
18:30:18.201 [pimatic] Error: socket hang up
18:30:18.201 [pimatic]>    at createHangUpError (http.js:1472:15)
18:30:18.201 [pimatic]>    at Socket.socketOnEnd (http.js:1568:23)
18:30:18.201 [pimatic]>    at Socket.g (events.js:180:16)
18:30:18.201 [pimatic]>    at Socket.EventEmitter.emit (events.js:117:20)
18:30:18.201 [pimatic]>    at _stream_readable.js:920:16
18:30:18.201 [pimatic]>    at process._tickCallback (node.js:415:13)
18:30:18.212 [pimatic] Could not update variable woonkamer-ornamenten.colormode: socket hang up
18:30:18.215 [pimatic] Error: socket hang up
18:30:18.215 [pimatic]>    at createHangUpError (http.js:1472:15)
18:30:18.215 [pimatic]>    at Socket.socketOnEnd (http.js:1568:23)
18:30:18.215 [pimatic]>    at Socket.g (events.js:180:16)
18:30:18.215 [pimatic]>    at Socket.EventEmitter.emit (events.js:117:20)
18:30:18.215 [pimatic]>    at _stream_readable.js:920:16
18:30:18.215 [pimatic]>    at process._tickCallback (node.js:415:13)
18:30:18.219 [pimatic] Could not update variable woonkamer-ornamenten.ct: socket hang up
18:30:18.224 [pimatic] Error: socket hang up
18:30:18.224 [pimatic]>    at createHangUpError (http.js:1472:15)
18:30:18.224 [pimatic]>    at Socket.socketOnEnd (http.js:1568:23)
18:30:18.224 [pimatic]>    at Socket.g (events.js:180:16)
18:30:18.224 [pimatic]>    at Socket.EventEmitter.emit (events.js:117:20)
18:30:18.224 [pimatic]>    at _stream_readable.js:920:16
18:30:18.224 [pimatic]>    at process._tickCallback (node.js:415:13)
18:30:18.297 [pimatic-hap] [fa:fe:db:e4:36:2c] HAP Request: POST /pair-verify
18:30:18.309 [pimatic-hap] [fa:fe:db:e4:36:2c] Pair verify step 2/2
18:30:18.337 [pimatic-hap] [fa:fe:db:e4:36:2c] Client AB16CF01-18CA-4E1C-857A-686746F1C6D6 verification complete
18:30:18.835 [pimatic-hue-zll] Received light 9 state change: {"on":true,"bri":147,"hue":14529,"sat":160,"effect":"none","xy":[0.4708,0.4124],"ct":389,"alert":"none","colormode":"xy","reachable":true}
18:30:18.874 [pimatic-hap] [fa:fe:db:e4:36:2c] HAP Request: GET /accessories
18:30:20.713 [pimatic-hue-zll] Hue API request failed: socket hang up
18:30:20.721 [pimatic] Could not get attribute value of Bank.state: socket hang up
18:30:20.724 [pimatic] Error: socket hang up
18:30:20.724 [pimatic]>    at createHangUpError (http.js:1472:15)
18:30:20.724 [pimatic]>    at Socket.socketOnEnd (http.js:1568:23)
18:30:20.724 [pimatic]>    at Socket.g (events.js:180:16)
18:30:20.724 [pimatic]>    at Socket.EventEmitter.emit (events.js:117:20)
18:30:20.724 [pimatic]>    at _stream_readable.js:920:16
18:30:20.724 [pimatic]>    at process._tickCallback (node.js:415:13)
18:30:20.729 [pimatic] Could not get attribute value of Bank.reachable: socket hang up
18:30:20.732 [pimatic] Error: socket hang up
18:30:20.732 [pimatic]>    at createHangUpError (http.js:1472:15)
18:30:20.732 [pimatic]>    at Socket.socketOnEnd (http.js:1568:23)
18:30:20.732 [pimatic]>    at Socket.g (events.js:180:16)
18:30:20.732 [pimatic]>    at Socket.EventEmitter.emit (events.js:117:20)
18:30:20.732 [pimatic]>    at _stream_readable.js:920:16
18:30:20.732 [pimatic]>    at process._tickCallback (node.js:415:13)
18:30:20.736 [pimatic] Could not get attribute value of Bank.dimlevel: socket hang up
18:30:20.739 [pimatic] Error: socket hang up
18:30:20.739 [pimatic]>    at createHangUpError (http.js:1472:15)
18:30:20.739 [pimatic]>    at Socket.socketOnEnd (http.js:1568:23)
18:30:20.739 [pimatic]>    at Socket.g (events.js:180:16)
18:30:20.739 [pimatic]>    at Socket.EventEmitter.emit (events.js:117:20)
18:30:20.739 [pimatic]>    at _stream_readable.js:920:16
18:30:20.739 [pimatic]>    at process._tickCallback (node.js:415:13)
18:30:20.748 [pimatic] Could not get attribute value of Bank.hue: socket hang up
18:30:20.751 [pimatic] Error: socket hang up
18:30:20.751 [pimatic]>    at createHangUpError (http.js:1472:15)
18:30:20.751 [pimatic]>    at Socket.socketOnEnd (http.js:1568:23)
18:30:20.751 [pimatic]>    at Socket.g (events.js:180:16)
18:30:20.751 [pimatic]>    at Socket.EventEmitter.emit (events.js:117:20)
18:30:20.751 [pimatic]>    at _stream_readable.js:920:16
18:30:20.751 [pimatic]>    at process._tickCallback (node.js:415:13)
18:30:20.755 [pimatic] Could not get attribute value of Bank.sat: socket hang up
18:30:20.758 [pimatic] Error: socket hang up
18:30:20.758 [pimatic]>    at createHangUpError (http.js:1472:15)
18:30:20.758 [pimatic]>    at Socket.socketOnEnd (http.js:1568:23)
18:30:20.758 [pimatic]>    at Socket.g (events.js:180:16)
18:30:20.758 [pimatic]>    at Socket.EventEmitter.emit (events.js:117:20)
18:30:20.758 [pimatic]>    at _stream_readable.js:920:16
18:30:20.758 [pimatic]>    at process._tickCallback (node.js:415:13)
18:30:20.762 [pimatic] Could not get attribute value of Bank.colormode: socket hang up
18:30:20.766 [pimatic] Error: socket hang up
18:30:20.766 [pimatic]>    at createHangUpError (http.js:1472:15)
18:30:20.766 [pimatic]>    at Socket.socketOnEnd (http.js:1568:23)
18:30:20.766 [pimatic]>    at Socket.g (events.js:180:16)
18:30:20.766 [pimatic]>    at Socket.EventEmitter.emit (events.js:117:20)
18:30:20.766 [pimatic]>    at _stream_readable.js:920:16
18:30:20.766 [pimatic]>    at process._tickCallback (node.js:415:13)
18:30:20.771 [pimatic] Could not get attribute value of Bank.ct: socket hang up
18:30:20.774 [pimatic] Error: socket hang up
18:30:20.774 [pimatic]>    at createHangUpError (http.js:1472:15)
18:30:20.774 [pimatic]>    at Socket.socketOnEnd (http.js:1568:23)
18:30:20.774 [pimatic]>    at Socket.g (events.js:180:16)
18:30:20.774 [pimatic]>    at Socket.EventEmitter.emit (events.js:117:20)
18:30:20.774 [pimatic]>    at _stream_readable.js:920:16
18:30:20.774 [pimatic]>    at process._tickCallback (node.js:415:13)
18:30:20.779 [pimatic] Could not update variable woonkamer-bank.state: socket hang up
18:30:20.782 [pimatic] Error: socket hang up
18:30:20.782 [pimatic]>    at createHangUpError (http.js:1472:15)
18:30:20.782 [pimatic]>    at Socket.socketOnEnd (http.js:1568:23)
18:30:20.782 [pimatic]>    at Socket.g (events.js:180:16)
18:30:20.782 [pimatic]>    at Socket.EventEmitter.emit (events.js:117:20)
18:30:20.782 [pimatic]>    at _stream_readable.js:920:16
18:30:20.782 [pimatic]>    at process._tickCallback (node.js:415:13)
18:30:20.786 [pimatic] Could not update variable woonkamer-bank.reachable: socket hang up
18:30:20.789 [pimatic] Error: socket hang up
18:30:20.789 [pimatic]>    at createHangUpError (http.js:1472:15)
18:30:20.789 [pimatic]>    at Socket.socketOnEnd (http.js:1568:23)
18:30:20.789 [pimatic]>    at Socket.g (events.js:180:16)
18:30:20.789 [pimatic]>    at Socket.EventEmitter.emit (events.js:117:20)
18:30:20.789 [pimatic]>    at _stream_readable.js:920:16
18:30:20.789 [pimatic]>    at process._tickCallback (node.js:415:13)
18:30:20.793 [pimatic] Could not update variable woonkamer-bank.dimlevel: socket hang up
18:30:20.796 [pimatic] Error: socket hang up
18:30:20.796 [pimatic]>    at createHangUpError (http.js:1472:15)
18:30:20.796 [pimatic]>    at Socket.socketOnEnd (http.js:1568:23)
18:30:20.796 [pimatic]>    at Socket.g (events.js:180:16)
18:30:20.796 [pimatic]>    at Socket.EventEmitter.emit (events.js:117:20)
18:30:20.796 [pimatic]>    at _stream_readable.js:920:16
18:30:20.796 [pimatic]>    at process._tickCallback (node.js:415:13)
18:30:20.800 [pimatic] Could not update variable woonkamer-bank.hue: socket hang up
18:30:20.803 [pimatic] Error: socket hang up
18:30:20.803 [pimatic]>    at createHangUpError (http.js:1472:15)
18:30:20.803 [pimatic]>    at Socket.socketOnEnd (http.js:1568:23)
18:30:20.803 [pimatic]>    at Socket.g (events.js:180:16)
18:30:20.803 [pimatic]>    at Socket.EventEmitter.emit (events.js:117:20)
18:30:20.803 [pimatic]>    at _stream_readable.js:920:16
18:30:20.803 [pimatic]>    at process._tickCallback (node.js:415:13)
18:30:20.808 [pimatic] Could not update variable woonkamer-bank.sat: socket hang up
18:30:20.811 [pimatic] Error: socket hang up
18:30:20.811 [pimatic]>    at createHangUpError (http.js:1472:15)
18:30:20.811 [pimatic]>    at Socket.socketOnEnd (http.js:1568:23)
18:30:20.811 [pimatic]>    at Socket.g (events.js:180:16)
18:30:20.811 [pimatic]>    at Socket.EventEmitter.emit (events.js:117:20)
18:30:20.811 [pimatic]>    at _stream_readable.js:920:16
18:30:20.811 [pimatic]>    at process._tickCallback (node.js:415:13)
18:30:20.815 [pimatic] Could not update variable woonkamer-bank.colormode: socket hang up
18:30:20.818 [pimatic] Error: socket hang up
18:30:20.818 [pimatic]>    at createHangUpError (http.js:1472:15)
18:30:20.818 [pimatic]>    at Socket.socketOnEnd (http.js:1568:23)
18:30:20.818 [pimatic]>    at Socket.g (events.js:180:16)
18:30:20.818 [pimatic]>    at Socket.EventEmitter.emit (events.js:117:20)
18:30:20.818 [pimatic]>    at _stream_readable.js:920:16
18:30:20.818 [pimatic]>    at process._tickCallback (node.js:415:13)
18:30:20.823 [pimatic] Could not update variable woonkamer-bank.ct: socket hang up
18:30:20.826 [pimatic] Error: socket hang up
18:30:20.826 [pimatic]>    at createHangUpError (http.js:1472:15)
18:30:20.826 [pimatic]>    at Socket.socketOnEnd (http.js:1568:23)
18:30:20.826 [pimatic]>    at Socket.g (events.js:180:16)
18:30:20.826 [pimatic]>    at Socket.EventEmitter.emit (events.js:117:20)
18:30:20.826 [pimatic]>    at _stream_readable.js:920:16
18:30:20.826 [pimatic]>    at process._tickCallback (node.js:415:13)
18:30:22.152 [pimatic-hue-zll] Hue API request failed: socket hang up
18:30:22.158 [pimatic] Could not get attribute value of Toilet.state: socket hang up
18:30:22.161 [pimatic] Error: socket hang up
18:30:22.161 [pimatic]>    at createHangUpError (http.js:1472:15)
18:30:22.161 [pimatic]>    at Socket.socketOnEnd (http.js:1568:23)
18:30:22.161 [pimatic]>    at Socket.g (events.js:180:16)
18:30:22.161 [pimatic]>    at Socket.EventEmitter.emit (events.js:117:20)
18:30:22.161 [pimatic]>    at _stream_readable.js:920:16
18:30:22.161 [pimatic]>    at process._tickCallback (node.js:415:13)
18:30:22.165 [pimatic] Could not get attribute value of Toilet.reachable: socket hang up
18:30:22.168 [pimatic] Error: socket hang up
18:30:22.168 [pimatic]>    at createHangUpError (http.js:1472:15)
18:30:22.168 [pimatic]>    at Socket.socketOnEnd (http.js:1568:23)
18:30:22.168 [pimatic]>    at Socket.g (events.js:180:16)
18:30:22.168 [pimatic]>    at Socket.EventEmitter.emit (events.js:117:20)
18:30:22.168 [pimatic]>    at _stream_readable.js:920:16
18:30:22.168 [pimatic]>    at process._tickCallback (node.js:415:13)
18:30:22.172 [pimatic] Could not get attribute value of Toilet.dimlevel: socket hang up
18:30:22.175 [pimatic] Error: socket hang up
18:30:22.175 [pimatic]>    at createHangUpError (http.js:1472:15)
18:30:22.175 [pimatic]>    at Socket.socketOnEnd (http.js:1568:23)
18:30:22.175 [pimatic]>    at Socket.g (events.js:180:16)
18:30:22.175 [pimatic]>    at Socket.EventEmitter.emit (events.js:117:20)
18:30:22.175 [pimatic]>    at _stream_readable.js:920:16
18:30:22.175 [pimatic]>    at process._tickCallback (node.js:415:13)
18:30:22.180 [pimatic] Could not update variable beneden-toilet.state: socket hang up
18:30:22.183 [pimatic] Error: socket hang up
18:30:22.183 [pimatic]>    at createHangUpError (http.js:1472:15)
18:30:22.183 [pimatic]>    at Socket.socketOnEnd (http.js:1568:23)
18:30:22.183 [pimatic]>    at Socket.g (events.js:180:16)
18:30:22.183 [pimatic]>    at Socket.EventEmitter.emit (events.js:117:20)
18:30:22.183 [pimatic]>    at _stream_readable.js:920:16
18:30:22.183 [pimatic]>    at process._tickCallback (node.js:415:13)
18:30:22.187 [pimatic] Could not update variable beneden-toilet.reachable: socket hang up
18:30:22.190 [pimatic] Error: socket hang up
18:30:22.190 [pimatic]>    at createHangUpError (http.js:1472:15)
18:30:22.190 [pimatic]>    at Socket.socketOnEnd (http.js:1568:23)
18:30:22.190 [pimatic]>    at Socket.g (events.js:180:16)
18:30:22.190 [pimatic]>    at Socket.EventEmitter.emit (events.js:117:20)
18:30:22.190 [pimatic]>    at _stream_readable.js:920:16
18:30:22.190 [pimatic]>    at process._tickCallback (node.js:415:13)
18:30:22.194 [pimatic] Could not update variable beneden-toilet.dimlevel: socket hang up
18:30:22.198 [pimatic] Error: socket hang up
18:30:22.198 [pimatic]>    at createHangUpError (http.js:1472:15)
18:30:22.198 [pimatic]>    at Socket.socketOnEnd (http.js:1568:23)
18:30:22.198 [pimatic]>    at Socket.g (events.js:180:16)
18:30:22.198 [pimatic]>    at Socket.EventEmitter.emit (events.js:117:20)
18:30:22.198 [pimatic]>    at _stream_readable.js:920:16
18:30:22.198 [pimatic]>    at process._tickCallback (node.js:415:13)
18:30:22.306 [pimatic-hue-zll] Received group 1 state change: {"on":true,"bri":147,"hue":14529,"sat":160,"effect":"none","xy":[0.4708,0.4124],"ct":389,"alert":"none","colormode":"xy"}
18:30:22.718 [pimatic-hue-zll] Received group 4 state change: {"on":true,"bri":147,"hue":14529,"sat":160,"effect":"none","xy":[0.4708,0.4124],"ct":389,"alert":"none","colormode":"xy"}
18:30:22.866 [pimatic-hue-zll] Received group 3 state change: {"on":false,"bri":190,"alert":"none"}
18:30:22.962 [pimatic-hue-zll] Received light 7 state change: {"on":false,"bri":152,"alert":"none","reachable":true}
18:30:23.042 [pimatic-hue-zll] Received light 4 state change: {"on":true,"bri":212,"hue":14529,"sat":160,"effect":"none","xy":[0.4708,0.4124],"ct":389,"alert":"none","colormode":"xy","reachable":true}
18:30:23.073 [pimatic-hue-zll] Received light 5 state change: {"on":false,"bri":203,"alert":"none","reachable":true}
18:30:23.082 [pimatic-hue-zll] Received light 8 state change: {"on":true,"bri":96,"hue":14529,"sat":160,"effect":"none","xy":[0.4708,0.4124],"ct":389,"alert":"none","colormode":"xy","reachable":true}
```

**Comment by sweebee** [comment]
in a rule to see if it was turned on:

```
18:34:01.285 [pimatic] Error on evaluation of rule condition of rule test: socket hang up
18:34:01.290 [pimatic] Error: socket hang up
18:34:01.290 [pimatic]>    at createHangUpError (http.js:1472:15)
18:34:01.290 [pimatic]>    at Socket.socketOnEnd (http.js:1568:23)
18:34:01.290 [pimatic]>    at Socket.g (events.js:180:16)
18:34:01.290 [pimatic]>    at Socket.EventEmitter.emit (events.js:117:20)
18:34:01.290 [pimatic]>    at _stream_readable.js:920:16
18:34:01.290 [pimatic]>    at process._tickCallback (node.js:415:13)
```

**Comment by sweebee** [comment]
I don't get any socket hangups in pimatic 0.9

**Comment by markbergsma** [comment]
Good to hear.

Even in Pimatic 0.8 (nodejs 0.10) it should work better now, I've completely redone error handling in pimatic-hue-zll. That means that where errors (socket hangups/connection resets in particular) still occur, it will retry and hide the error most of the time (unless debug logging is enabled).

**Comment by sweebee** [comment]
Works great!
