### ISSUE TITLE
[pimatic v0.9] bug in gui edit/add group light.

### ISSUE THREAD

**Issue by sweebee** [markbergsma/pimatic-hue-zll#7]
Not yet important but in pimatic v0.9 you can add devices trough the gui. For 'normal' hue devices it works fine, but the grouped ones don't. I get: ```error [pimatic-hue-zll]: Error while polling light group 3 status: @lightStatusResult?.state?``` 

Sweetpi will release a 'readme' for how to handle devices through gui. But maybe you can find it already since the error does not occur with not grouped devices.

**Comment by sweebee** [comment]
Sweetpi released info about destroying a device. Might be something to to with this? He also explained the auto discovery.

https://github.com/pimatic/pimatic/issues/859

**Comment by sweebee** [comment]
Last commit did improve some stuff, but i can't turn de the device on:

```

12:53:43.291 [pimatic-hue-zll] debug: Received group 9 state change: {"on":false,"bri":157,"alert":"none"}
12:53:43.390 [pimatic-hue-zll] debug: Changing group 9 state: {"on":true}
12:53:43.400 [pimatic] error: Cannot set property 'on' of undefined
12:53:43.412 [pimatic] debug: TypeError: Cannot set property 'on' of undefined
12:53:43.412 [pimatic] debug:>    at BaseHueLightGroup.BaseHueLight._mergeStateChange (/home/pi/pimatic-app/node_modules/pimatic-hue-zll/hue.coffee:217:7)
12:53:43.412 [pimatic] debug:>    at /home/pi/pimatic-app/node_modules/pimatic-hue-zll/hue.coffee:256:10
12:53:43.412 [pimatic] debug:>    at tryCatcher (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/util.js:16:23)
12:53:43.412 [pimatic] debug:>    at Promise._settlePromiseFromHandler (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/promise.js:503:31)
12:53:43.412 [pimatic] debug:>    at Promise._settlePromise (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/promise.js:560:18)
12:53:43.412 [pimatic] debug:>    at Promise._settlePromise0 (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/promise.js:605:10)
12:53:43.412 [pimatic] debug:>    at Promise._settlePromises (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/promise.js:684:18)
12:53:43.412 [pimatic] debug:>    at Async._drainQueue (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/async.js:126:16)
12:53:43.412 [pimatic] debug:>    at Async._drainQueues (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/async.js:136:10)
12:53:43.412 [pimatic] debug:>    at Immediate.Async.drainQueues [as _onImmediate] (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/async.js:16:14)
12:53:43.412 [pimatic] debug:>    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

**Comment by markbergsma** [comment]
Better now with commit e126d08?

Unfortunately I haven't been able to reproduce this in my setup; it may depend on the Hue bridge version or something.

**Comment by sweebee** [comment]
Yes works.
